config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations', sesions: 'sessions'}
  match 'remote_sign_up', to: 'remote_content#remote_sign_up', via: [:get]
  match 'remote_sign_in', to: 'remote_content#remote_sign_in', via: [:get]
  root to: 'high_voltage/pages#show', id: 'home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

 def create
 build_resource(sign_up_params)

 if resource.save
 respond_to do |format|
 format.html {
 yield resource if block_given?
 if resource.active_for_authentication?
 set_flash_message :notice, :signed_up if is_flashing_format?
 sign_up(resource_name, resource)
 respond_with resource, :location => after_sign_up_path_for(resource)
 else
 set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
 expire_data_after_sign_in!
 respond_with resource, :location => after_inactive_sign_up_path_for(resource)
 end
 }
 format.js {
 flash[:notice] = "Created account, signed in."
 render :template => "remote_content/devise_success_sign_up.js.erb"
 flash.discard
 sign_up(resource_name, resource)
 }
 end
 else
 respond_to do |format|
 format.html {
 clean_up_passwords resource
 respond_with resource
 }
 format.js {
 flash[:alert] = @user.errors.full_messages.to_sentence
 render :template => "remote_content/devise_errors.js.erb"
 flash.discard
 }
 end
 end
 end
end

app/controllers/remote_content_controller.rb
class RemoteContentController < ApplicationController
end

app/controllers/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
protect_from_forgery with: :null_session

def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_flashing_format?
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_normal
   render "flashes"
  end
  def twitterized_type(type)
    case type
    when :errors
    "alert-error"
    when :alert
    "alert-warning"
    when :error
    "alert-error"
    when :notice
    "alert-success"
    else
    "alert-info"
    end
  end
  def resource_name
   :user
  end

  def resource
   @resource ||= User.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/remote_content_helper.rb
module RemoteContentHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/application/_flashes.html.haml
#flash
 - flash.each do |type, message|
  .alert.alert-dismissable{ :class => twitterized_type(type) }
  %button.close{"data-dismiss" => "alert", "aria-hidden" => "true"} ×
  %p= message

app/views/layouts/application.html.haml
!!!
%html
 %head
  %meta{charset: "utf-8"}
  %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no", name: "viewport"}
  %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
  = stylesheet_link_tag :application, :media => 'all'
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
 %title
  = yield(:title)
 %body
  = render 'flashes'
  = yield

app/views/pages/home.html.haml
- content_for(:title, 'This is our home page view')
%nav.navbar.navbar-default{role: "navigation"}
 .container
  .navbar-header
   %button.navbar-toggle{"data-target" => "#nav-collapse", "data-toggle" => "collapse", type: "button"}
   %span.sr-only Toggle navigation
   %span.icon-bar
   %span.icon-bar
   %span.icon-bar
   %a.navbar-brand{href: root_path}
   %span Devise_ajax
  #nav-collapse.collapse.navbar-collapse
   %ul.nav.navbar-nav
    %li.dropdown
     %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
      Menu
      %b.caret
      %ul.dropdown-menu
       - if current_user
        %li
         = link_to "Sign out", destroy_user_session_path, "data-method" => :delete
       - else
        %li
         = link_to "Sign up", remote_sign_up_path, :remote => true
        %li
         = link_to "Sign in", remote_sign_in_path, :remote => true
   .container
    .row
     .col-xs-12
      - if current_user
       %h1 You Are Logged IN!!!!!!!
      - else
       %h1 You Are Not Currently logged in

app/views/remote_content/_remote_sign_in.html.haml
#sign_in_modal.modal
 .container1
  .modal-dialog
  .modal-content
  .modal-header
   %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"}
   %i.fa.fa-times-circle
   %h4#SignInModal.modal-title Sign into acount
  = simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :remote => true, :format => :js, :html => {:class => "form-signin"}) do |f|
   .modal-body
    = text_field_tag 'user[email]'
    %br
    = password_field_tag 'user[password]'
    %br
    = check_box_tag 'user[remember_me]'
    = label_tag 'user[remember_me]', 'Remember me'
    %br
   .footer
    .form-actions
     %button Sign in
     %br
     = link_to "Forgot your password?", new_password_path(:user)

app/views/remote_content/_remote_sign_up.html.haml
#sign_up_modal.modal
 .container1
  .modal-dialog
  .modal-content
   %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"}
   %i.fa.fa-times-circle
   %h4#SignInModal.title Create an account
   %p Add your details to create an account
  .modal-header
  = simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :remote => true, :format => :js, :html => {:class => "form-signin"}) do |f|
   .modal-body
    = f.input :email, :autofocus => true, :label => false, :placeholder => "Email"
    = f.input :password, :label => false, :placeholder => "Password"
    = f.input :password_confirmation, :label => false, :placeholder => "Confirm password"
    = link_to "Already have an account?", new_user_session_path
    %br
    = link_to "Forgot your password?", new_user_password_path
   .footer
    .form-actions
     %a{ :href => "#", "data-dismiss" => "modal" } Cancel
     = f.button :submit, "Create account"

app/views/remote_content/remote_sign_in.js.erb
if($('.modal').length > 0) {
 $("#sign_in_modal").modal();
}
else {
 $("body").prepend("<%= escape_javascript(render "remote_sign_in", :formats => [:html]) %>");
 $("#sign_in_modal").modal();
}

app/views/remote_content/remote_sign_up.js.erb
if($('.modal').length > 0) {
 $("#sign_up_modal").modal();
}
else {
 $("body").prepend("<%= escape_javascript(render "remote_sign_up", :formats => [:html]) %>");
 $("#sign_up_modal").modal();
}